### ISSUE TITLE
Gear list opening unreadable in wrong location

### ISSUE THREAD

**Issue by cidrei** [NeNeppie/AvantGarde#3]
Opening the AvantGarde lists near the left edge of the screen causes them to appear in the upper left corner with a teeny tiny font.

Steps to reproduce:
1) Ask Masked Rose to confirm this week's fashion challenge.
2) Move the Fashion Report window to the left edge of the screen.
3) Click one of the Show Gear buttons.
4) List will appear in a black box in the upper left corner in an unreadable size.

![a-g_bug](https://github.com/NeNeppie/AvantGarde/assets/55462924/bc5fa1d9-e2f2-4efc-a9c3-cd02dae4aee3)

**Comment by NeNeppie** [comment]
Can't replicate. Could you provide more info? Does this happen with other plugins too (and are you using any third party plugins)? Was the red border there?

**Comment by cidrei** [comment]
My apologies for the false report. It's not actually this plugin but some kind of interaction between Dalamud's windows and [Special K](https://www.special-k.info/), which didn't even occur to me to might be the problem. This addon just happened to be the first one I triggered it with. The red border was added by me for clarity.

I'll close the report as it's unrelated to this addon.

Sorry!
